# gunicorn.conf.py
bind = "0.0.0.0:8000"
workers = 4  # Can increase back to 4 since video processing is offloaded
worker_class = "gthread" # Or keep "gthread" if you have many concurrent uploads
timeout = 300
graceful_timeout = 300
keepalive = 5




"""bind = "0.0.0.0:8000"
workers = 2  # Reduced from 4 to lower memory pressure
worker_class = "gthread"  # Switch to threaded workers for better I/O handling
threads = 4  # Increased threads per worker to handle concurrent requests
timeout = 300
graceful_timeout = 300
keepalive = 5
errorlog = "-"
accesslog = "-"
loglevel = "info""""







"""# gunicorn.conf.py
bind = "0.0.0.0:8000"
workers = 4
worker_class = "sync"
threads = 2
timeout = 300
graceful_timeout = 300
keepalive = 5
errorlog = "-"
accesslog = "-"
loglevel = "info""""