"""
Django settings for fed_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config
import os
from pathlib import Path

from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.environ.get('SECRET_KEY', 'fallback-key')
#SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.environ.get('DEBUG','False')== 'True'



# Get ALLOWED_HOSTS from environment variable, or use a safe default for Koyeb
# In production on Koyeb, we often need to allow the internal UUIDs or all hosts

# Trust the proxy headers from Koyeb/Cloudflare
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Allow all hosts on koyeb
#ALLOWED_HOSTS = ['*']

# Optional: Force HTTPS in production (recommended)
# SECURE_SSL_REDIRECT = True 
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
#CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['GET','POST','PUT', 'PATCH','DELETE','OPTIONS']
CORS_ALLOW_HEADERS = ['range', 'content-type', 'authorization']

env_hosts = os.environ.get('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS = [h.strip() for h in env_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        '.koyeb.app', 
        'localhost', 
        '127.0.0.1',
        'prime-cordi-fed-devo-7c4aa839.koyeb.app',
    ]
    
    # Corrected Koyeb platform environment checks (Uppercase)
    if os.environ.get('KOYEB_SERVICE_ID') or os.environ.get('KOYEB_APP_NAME'):
        ALLOWED_HOSTS.append('*')

"""
env_hosts = os.environ.get('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS = [h.strip() for h in env_hosts.split(',') if h.strip()]
else:
    # Default for Koyeb: Allow the domain wildcard and localhost
    # This covers both 'prime-cordi...koyeb.app' and internal UUIDs if they resolve correctly
    # If internal UUIDs still fail, we allow all hosts (safe behind Koyeb's proxy)
    ALLOWED_HOSTS = [
        '.koyeb.app', 
        'localhost', 
        '127.0.0.1',
        'prime-cordi-fed-devo-7c4aa839.koyeb.app',
        # Add a fallback to allow all hosts if running on Koyeb (since internal routing is dynamic)
        # This is safe because Koyeb's load balancer handles the external traffic
    ]
    
    # Optional: If you want to be extra safe and allow the internal UUIDs explicitly
    # You can add a check or just allow all hosts in production
    if os.environ.get('Koyeb') or os.environ.get('Koyeb_Deployment_ID'):
        ALLOWED_HOSTS.append('*') # Allow all hosts in Koyeb environment"""




# 2. Add your Vercel production URL here
# Replace 'https://your-vercel-app.vercel.app' with your actual Vercel URL
CSRF_TRUSTED_ORIGINS = [
    'https://fed-educate-three.vercel.app', 
    'https://fed-educ-jxwtbwqee-sendawula-freds-projects.vercel.app/'
    'https://fed-educ-2o2zlqosy-sendawula-freds-projects.vercel.app',
    'https://prime-cordi-fed-devo-7c4aa839.koyeb.app/'
    #'prime-cordi-fed-devo-7c4aa839.koyeb.app', # Keep this only if you test via Koyel preview
    'http://localhost:3000', # For local development
    'http://localhost:5173' # For local development with Vite
]

# 3. Ensure CORS is configured (if using django-cors-headers)
CORS_ALLOWED_ORIGINS = [
    'https://fed-educate-three.vercel.app',
    'http://localhost:3000',
    'http://localhost:5173'
]

#CSRF_TRUSTED_ORIGINS = ['https://prime-cordi-fed-devo-7c4aa839.koyeb.app']

#ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,https://prime-cordi-fed-devo-7c4aa839.koyeb.app').split(',')
#LLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS]

#ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,*").split(",")
#CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="http://localhost:5173").split(",")



# Application definition

INSTALLED_APPS = [
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #myapps
    'users',
    'content',
    'media_manager',
    'media_external_manager',
    'section',
    'quiz',
    'question',
    'comparison',
    'caseStudy',
    'benefits',
    'drawbacks',
    'UserQuizResponse',
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    'drf_spectacular',
    'gunicorn',
    'allauth.account',
    "whitenoise",
    'storages',
    #'storages.backend.s3boto3',
    'celery',  

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <- MOVE THIS TO LINE 1
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #'fed_api.middleware.MediaCORSHeaderMiddleware', # Add this line
    

]

"""MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
"""
# ---- IMPORTANT: Custom User Model ----
AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'fed_api.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fed_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import os
"""
# Determine if we are connecting to an external host
db_host = os.environ.get('DB_HOST', 'db')
is_external = not db_host.startswith('db') and not db_host.startswith('localhost')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': db_host,
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            # Only require SSL for external hosts (e.g., Koyeb)
            'sslmode': 'require' if is_external else 'prefer', 
        }
    }
}"""

DATABASES = {
    'default': {
        'ENGINE':  'django.db.backends.sqlite3',
        'NAME': 'db.sqlite'
    }
}






# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# FILE UPLOAD SETTINGS
# ============================================================================

# Maximum file upload size (500MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB

# Allowed file extensions
FILE_UPLOAD_PERMISSIONS = 0o644

# Temporary file location
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'tmp')



# ============================================================================
# EXTERNAL MEDIA MANAGER SETTINGS
# ============================================================================

# Supported external sources
EXTERNAL_MEDIA_SOURCES = {
    'youtube': {
        'name': 'YouTube',
        'enabled': True,
        'timeout': 10,
    },
    'vimeo': {
        'name': 'Vimeo',
        'enabled': True,
        'timeout': 10,
    },
    'google_drive': {
        'name': 'Google Drive',
        'enabled': True,
        'timeout': 10,
    },
    'facebook': {
        'name': 'Facebook',
        'enabled': True,
        'timeout': 10,
    },
    'direct': {
        'name': 'Direct URL',
        'enabled': True,
        'timeout': 10,
    },
}

# Thumbnail settings
EXTERNAL_MEDIA_THUMBNAIL_SIZE = (300, 300)
EXTERNAL_MEDIA_THUMBNAIL_QUALITY = 85
EXTERNAL_MEDIA_THUMBNAIL_FORMAT = 'JPEG'

# Timeout for external requests
EXTERNAL_MEDIA_REQUEST_TIMEOUT = 10

# Maximum retries for failed requests
EXTERNAL_MEDIA_MAX_RETRIES = 3

# Cache settings for external media metadata
EXTERNAL_MEDIA_CACHE_TIMEOUT = 3600  # 1 hour

# ============================================================================
# CACHING CONFIGURATION
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'media_external',
        'TIMEOUT': 3600,
    }
}

# Fallback to local memory cache if Redis is not available
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        #'django_filter.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

from datetime import timedelta
SIMPLE_JWT = {
    
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    #'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    #'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

}
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}"""



# CORS Settings
#CORS_ALLOW_ALL_ORIGINS = False
#CORS_ALLOW_CREDENTIALS = True
#CORS_ALLOWED_ORIGINS = [
    #"http://localhost:5173",
    #"http://localhost:3000",
    #"http://localhost:8080",
    #"http://127.0.0.1:3000",
    #"http://127.0.0.1:8000",
    #'https://prime-cordi-fed-devo-7c4aa839.koyeb.app',
#] 
# Allow specific headers for video streaming
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'range',  # Important for video seeking
]

#CORS_ALLOW_ALL_ORIGINS = False
#CORS_ALLOW_CREDENTIALS = True






#CORS_ALLOWED_ORIGINS = config(
    #'CORS_ALLOWED_ORIGINS',
    #default='http://localhost:5173,http://localhost:3000'
#).split(',')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CORS_ALLOW_CREDENTIALS = True



# Create directories if they don't exist
os.makedirs(os.path.join(BASE_DIR, 'tmp'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'static'), exist_ok=True)

# Use the created directories
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'tmp')

#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Celery Configuration
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Tedis also works on 6379
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"  # use db 1 for results/progress
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# In your celery.py file, ensure it loads these settings
# app.config_from_object('django.conf:settings', namespace='CELERY')


# Tell Django to use S3 backend
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Put your Supabase S3 credentials here
AWS_ACCESS_KEY_ID = os.environ.get('SUPABASE_S3_ACCESS_KEY_ID', os.environ.get('AWS_ACCESS_KEY_ID', '90c5e783dda69413c813b49fdbfbc0a0'))
AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_S3_SECRET_ACCESS_KEY', os.environ.get('AWS_SECRET_ACCESS_KEY', '723132c9d8f3931e48b120de87499567b1ee03c2b41cbbc149b5a7205d01777b'))
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'federalism-media')

# Connect directly to Supabase S3 API
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'https://uiomawuiijsqkvesfjvf.storage.supabase.co/storage/v1/s3')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', os.environ.get('AWS_S3_REGION', 'eu-west-1'))
AWS_DEFAULT_REGION = AWS_S3_REGION_NAME

# Supabase S3 compatibility settings
AWS_S3_ADDRESSING_STYLE = os.environ.get('AWS_S3_ADDRESSING_STYLE', 'path')
AWS_S3_SIGNATURE_VERSION = os.environ.get('AWS_S3_SIGNATURE_VERSION', 's3v4')
AWS_QUERYSTRING_AUTH = False  
AWS_S3_FILE_OVERWRITE = False

# For big files + avoid checksum crash
AWS_S3_DISABLE_CONTENT_MD5_VALIDATION = True
AWS_S3_MULTIPART_CHUNK_SIZE = 15 * 1024 * 1024

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Increase upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024 # 1GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 10242 # Critical things for Sup

# 6. Static files config (Whitenoise is great for production)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 7. Documentation (Brilliant job setting up drf-spectacular!)
SPECTACULAR_SETTINGS = {
    'TITLE': 'src_api API',
    'DESCRIPTION': 'API for the Federalism Education Platform',
    'VERSION': '1.0.0',
}