# Generated by Django 4.2.16 on 2026-05-02 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('google_drive', 'Google Drive'), ('facebook', 'Facebook'), ('vimeo', 'Vimeo'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=50)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document'), ('documentary', 'Documentary'), ('map', 'Map'), ('studycase', 'Study Case'), ('other', 'Other')], default='other', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(max_length=1024)),
                ('embed_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='media_external_manager.externalmedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['user', '-created_at'], name='media_exter_user_id_86283d_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['source_type', 'status'], name='media_exter_source__0f69c6_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['media_type', 'status'], name='media_exter_media_t_ce7f6c_idx'),
        ),
    ]
